import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class OwnerPromoManagementScreen extends StatefulWidget {
  final String restaurantId;
  final String restaurantName;
  const OwnerPromoManagementScreen({super.key, required this.restaurantId, required this.restaurantName});
  @override State<OwnerPromoManagementScreen> createState() => _OwnerPromoManagementScreenState();
}

class _OwnerPromoManagementScreenState extends State<OwnerPromoManagementScreen> {
  final _db = Supabase.instance.client;
  bool _loading = true;
  List<Map<String,dynamic>> _promos = [];
  @override void initState(){super.initState();_load();}
  Future<void> _load() async{if(mounted)setState(()=>_loading=true);try{final rows=await _db.from('promo_codes').select().eq('restaurant_id',widget.restaurantId).order('created_at',ascending:false);if(mounted)setState((){_promos=List<Map<String,dynamic>>.from(rows);_loading=false;});}catch(e){if(mounted){setState(()=>_loading=false);_msg('Unable to load promos: $e');}}}
  Future<void> _save({Map<String,dynamic>? promo}) async{
    final code=TextEditingController(text:promo?['code']?.toString()??''),title=TextEditingController(text:promo?['title']?.toString()??''),value=TextEditingController(text:promo?['discount_value']?.toString()??''),minimum=TextEditingController(text:promo?['minimum_order']?.toString()??'0');
    String type=promo?['discount_type']?.toString()??'percentage'; bool active=promo?['is_active']!=false; final form=GlobalKey<FormState>();
    final ok=await showDialog<bool>(context:context,builder:(ctx)=>StatefulBuilder(builder:(ctx,setLocal)=>AlertDialog(title:Text(promo==null?'Create Promo':'Edit Promo',style:const TextStyle(fontWeight:FontWeight.w800)),content:SizedBox(width:420,child:Form(key:form,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextFormField(controller:code,decoration:const InputDecoration(labelText:'Promo Code'),validator:(v)=>v==null||v.trim().isEmpty?'Required':null),TextFormField(controller:title,decoration:const InputDecoration(labelText:'Promo Title'),validator:(v)=>v==null||v.trim().isEmpty?'Required':null),DropdownButtonFormField<String>(value:type,decoration:const InputDecoration(labelText:'Discount Type'),items:const[DropdownMenuItem(value:'percentage',child:Text('Percentage')),DropdownMenuItem(value:'fixed',child:Text('Fixed Amount'))],onChanged:(v)=>setLocal(()=>type=v??'percentage')),TextFormField(controller:value,decoration:InputDecoration(labelText:type=='percentage'?'Discount Percentage':'Discount Amount'),keyboardType:const TextInputType.numberWithOptions(decimal:true),validator:(v)=>double.tryParse(v??'')==null?'Enter a valid amount':null),TextFormField(controller:minimum,decoration:const InputDecoration(labelText:'Minimum Order'),keyboardType:const TextInputType.numberWithOptions(decimal:true)),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Promo Active'),value:active,onChanged:(v)=>setLocal(()=>active=v))])))),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancel')),ElevatedButton(onPressed:(){if(form.currentState!.validate())Navigator.pop(ctx,true);},child:const Text('Save'))])));
    if(ok!=true){code.dispose();title.dispose();value.dispose();minimum.dispose();return;}
    final data={'restaurant_id':widget.restaurantId,'code':code.text.trim().toUpperCase(),'title':title.text.trim(),'discount_type':type,'discount_value':double.parse(value.text.trim()),'minimum_order':double.tryParse(minimum.text.trim())??0,'is_active':active};
    code.dispose();title.dispose();value.dispose();minimum.dispose();
    try{if(promo==null){await _db.from('promo_codes').insert(data);}else{await _db.from('promo_codes').update(data).eq('id',promo['id']).eq('restaurant_id',widget.restaurantId);}await _load();}catch(e){_msg('Unable to save promo: $e');}
  }
  Future<void> _toggle(Map<String,dynamic> p) async{try{await _db.from('promo_codes').update({'is_active':p['is_active']!=true}).eq('id',p['id']).eq('restaurant_id',widget.restaurantId);await _load();}catch(e){_msg('Unable to update promo: $e');}}
  Future<void> _delete(Map<String,dynamic> p) async{final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Delete Promo'),content:Text('Delete ${p['code']}?'),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancel')),ElevatedButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Delete'))]));if(ok!=true)return;try{await _db.from('promo_codes').delete().eq('id',p['id']).eq('restaurant_id',widget.restaurantId);await _load();}catch(e){_msg('Unable to delete promo: $e');}}
  void _msg(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Promos & Discounts',style:TextStyle(fontWeight:FontWeight.w800)),actions:[IconButton(onPressed:_loading?null:_load,icon:const Icon(Icons.refresh_rounded))]),floatingActionButton:FloatingActionButton.extended(onPressed:_loading?null:()=>_save(),icon:const Icon(Icons.add),label:const Text('Create Promo')),body:_loading?const Center(child:CircularProgressIndicator()):_promos.isEmpty?const Center(child:Text('No promos for this restaurant yet.')):RefreshIndicator(onRefresh:_load,child:ListView.builder(padding:const EdgeInsets.fromLTRB(16,16,16,100),itemCount:_promos.length,itemBuilder:(context,i){final p=_promos[i],type=p['discount_type'],v=p['discount_value'],active=p['is_active']==true;return Card(margin:const EdgeInsets.only(bottom:12),child:ListTile(onTap:()=>_save(promo:p),leading:const CircleAvatar(child:Icon(Icons.local_offer_rounded)),title:Text(p['code']?.toString()??'',style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${p['title']??''}\n${type=='percentage'?'$v% OFF':'₱$v OFF'}  •  Min ₱${p['minimum_order']??0}',maxLines:2),isThreeLine:true,trailing:Row(mainAxisSize:MainAxisSize.min,children:[Switch(value:active,onChanged:(_)=>_toggle(p)),IconButton(onPressed:()=>_delete(p),icon:const Icon(Icons.delete_outline,color:Colors.redAccent))]));})));}
