import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class AdminSubscriptionPaymentMethodsScreen extends StatefulWidget {
  const AdminSubscriptionPaymentMethodsScreen({super.key});
  @override State<AdminSubscriptionPaymentMethodsScreen> createState() => _AdminSubscriptionPaymentMethodsScreenState();
}
class _AdminSubscriptionPaymentMethodsScreenState extends State<AdminSubscriptionPaymentMethodsScreen> {
  final db = Supabase.instance.client;
  bool loading = true;
  List<Map<String,dynamic>> methods = [];
  @override void initState(){super.initState(); load();}
  Future<void> load() async { setState(()=>loading=true); try { final r=await db.from('subscription_payment_methods').select().order('sort_order').order('created_at'); if(mounted)setState(()=>methods=List<Map<String,dynamic>>.from(r as List)); } catch(e){if(mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Unable to load: $e')));} finally{if(mounted)setState(()=>loading=false);} }
  Future<void> save(Map<String,dynamic> v,String? id) async { try { if(id==null){await db.from('subscription_payment_methods').insert(v);}else{await db.from('subscription_payment_methods').update(v).eq('id',id);} await load(); if(mounted)Navigator.pop(context); } catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Unable to save: $e')));} }
  Future<void> toggle(Map<String,dynamic> m) async { try{await db.from('subscription_payment_methods').update({'is_active':m['is_active']!=true}).eq('id',m['id']);await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Unable to update: $e')));}}
  void form([Map<String,dynamic>? old]){ final fields=<String,TextEditingController>{for(final k in ['name','type','account_name','account_number','instructions','qr_code_url','sort_order'])k:TextEditingController(text:old?[k]?.toString()??(k=='type'?'gcash':k=='sort_order'?'${methods.length+1}':''))}; showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(c)=>Padding(padding:EdgeInsets.fromLTRB(20,10,20,MediaQuery.of(c).viewInsets.bottom+20),child:SingleChildScrollView(child:Column(children:[Text(old==null?'Add Payment Method':'Edit Payment Method',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w800)),const SizedBox(height:16),...fields.entries.map((e)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:e.value,maxLines:e.key=='instructions'?4:1,keyboardType:e.key=='sort_order'?TextInputType.number:null,decoration:InputDecoration(labelText:e.key.replaceAll('_',' ').toUpperCase())))),SizedBox(width:double.infinity,child:FilledButton(onPressed:(){final v=<String,dynamic>{'name':fields['name']!.text.trim(),'type':fields['type']!.text.trim().toLowerCase(),'account_name':_n(fields['account_name']!.text),'account_number':_n(fields['account_number']!.text),'instructions':_n(fields['instructions']!.text),'qr_code_url':_n(fields['qr_code_url']!.text),'sort_order':int.tryParse(fields['sort_order']!.text)??0,'updated_at':DateTime.now().toUtc().toIso8601String()};Navigator.pop(c);save(v,old?['id']?.toString());},child:const Text('Save Payment Method')))])))).whenComplete(()=>fields.values.forEach((x)=>x.dispose())); }
  String? _n(String x)=>x.trim().isEmpty?null:x.trim();
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Payment Methods',style:TextStyle(fontWeight:FontWeight.w800))),floatingActionButton:FloatingActionButton.extended(onPressed:()=>form(),icon:const Icon(Icons.add),label:const Text('Add Method')),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[const Text('Subscription Payment Methods',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:8),const Text('These enabled methods will be shown to restaurant owners during subscription.',style:TextStyle(color:Colors.grey)),const SizedBox(height:16),if(methods.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(20),child:Text('No payment methods configured yet.'))),...methods.map((m)=>Card(child:ListTile(leading:Icon(m['type']=='bank_transfer'?Icons.account_balance:Icons.account_balance_wallet),title:Text(m['name']??'Payment Method',style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text([m['account_name'],m['account_number']].where((x)=>x!=null&&x.toString().isNotEmpty).join(' • ')),trailing:Wrap(children:[Switch(value:m['is_active']==true,onChanged:(_)=>toggle(m)),IconButton(onPressed:()=>form(m),icon:const Icon(Icons.edit)),IconButton(onPressed:()async{await db.from('subscription_payment_methods').delete().eq('id',m['id']);await load();},icon:const Icon(Icons.delete_outline))])))])));
}
